# 1.Create a 2D Numpy array with shape (3, 3) containing random integers between 1 and 20.

In [8]:
import numpy as np
arr = np.random.randint(low = 1, high = 21 ,size = (3,3))
print(arr)

[[12 13  2]
 [ 4  5 18]
 [ 5 12  1]]


# 2.Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values for each row

In [20]:
import numpy as np
arr = np.random.random((5,5))
print(f"array:\n {arr}\n")
print(f"min in each row:\n {arr.min(axis=1)} \n max in each row: \n {arr.max(axis=1)} \n")

array:
 [[0.79889201 0.14840745 0.05059189 0.97183877 0.42292743]
 [0.20288494 0.21218077 0.12257286 0.86433033 0.33887845]
 [0.0804984  0.68025    0.53605821 0.23228578 0.77114472]
 [0.96678122 0.57880293 0.4923021  0.6667784  0.24134173]
 [0.38240067 0.18604152 0.52395266 0.29902463 0.41727813]]

min in each row:
 [0.05059189 0.12257286 0.0804984  0.24134173 0.18604152] 
 max in each row: 
[0.97183877 0.86433033 0.77114472 0.96678122 0.52395266] 



# 3.Write a NumPy program to create a random vector of size 10 and sort it.

In [31]:
import numpy as np
arr = np.random.random(10)
print(arr)
print(f"sorted array : {np.sort(arr)}")

[0.23504663 0.92752859 0.58036116 0.1126201  0.62623689 0.90125357
 0.97063714 0.60919622 0.17321957 0.20148293]
sorted array : [0.1126201  0.17321957 0.20148293 0.23504663 0.58036116 0.60919622
 0.62623689 0.90125357 0.92752859 0.97063714]


# 4.Write a NumPy program to find the most frequent value in an array.

In [43]:
import numpy as np

arr = np.array([0,1,2,3,1,4,5,5,5,5,5,5,5])
ar = np.bincount(arr)
maxs = ar.max()

for i in range(len(ar)):
    if ar[i] == maxs:
        most = i
        break

print(most)
        


[1 2 1 1 1 7]
7
5


# 5.Replace all even numbers in the 2D array with 0.

In [24]:
import numpy as np
arr = np.array([(1,2,3),(4,5,6)])
arr[arr % 2 == 0] = 0

print(arr)

[[1 0 3]
 [0 5 0]]


# 6.Apply the square root function to each element of the 1D array

In [32]:
import numpy as np
arr = np.random.random(5)
print(arr)
print(f"new : {np.sqrt(arr)}")

[0.51671692 0.7686627  0.48471142 0.08977344 0.86476378]
new : [0.71883024 0.87673411 0.69621219 0.29962217 0.92992676]


# 7.Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element.

In [49]:
import numpy as np
arr = np.random.rand(3,3)
mean = arr.mean(axis = 1, keepdims=True)

new = np.subtract(arr,mean)

print(new)

[[ 0.11605592  0.3067021  -0.45283377]
 [ 0.2062643  -0.41963924 -0.06958842]
 [ 0.13884044  0.10937915  0.06481952]]


# 8.Create a 1D array containing the first 20 odd numbers.

In [46]:
import numpy as np
arr = np.arange(1,40,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


# 9.Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.

In [72]:
import numpy as np 

arr = np.random.random((5,5))
print(arr ,"\n")

arr.sort(axis = 0)
print(arr,"\n")

for i in range(len(arr)):
    print(arr[-2][i])



[[0.68499791 0.83808216 0.53016292 0.17527781 0.49470544]
 [0.26351794 0.29722589 0.14480731 0.08913674 0.92611169]
 [0.88421449 0.76186579 0.95656595 0.76725687 0.78064292]
 [0.11672604 0.05653477 0.39309639 0.9557951  0.62472301]
 [0.41251932 0.02264264 0.84309281 0.40219218 0.58641295]] 

[[0.11672604 0.02264264 0.14480731 0.08913674 0.49470544]
 [0.26351794 0.05653477 0.39309639 0.17527781 0.58641295]
 [0.41251932 0.29722589 0.53016292 0.40219218 0.62472301]
 [0.68499791 0.76186579 0.84309281 0.76725687 0.78064292]
 [0.88421449 0.83808216 0.95656595 0.9557951  0.92611169]] 

0.684997908022911
0.7618657914721534
0.8430928052619496
0.7672568658476234
0.7806429247754484


# 10.Write a NumPy program to create a 4x4 array with random values and find the sum of each row.

In [80]:
import numpy as np

arr = np.random.random((4,4))
print(arr)

sum = arr.sum(axis=1)
print(sum)


[[0.3011951  0.29798266 0.41785589 0.7258607 ]
 [0.8392795  0.77946614 0.52056506 0.99358627]
 [0.55527193 0.88021529 0.42546035 0.15158546]
 [0.71663976 0.21310369 0.70969824 0.39755102]]
[1.74289435 3.13289698 2.01253302 2.03699272]
