In [28]:
import Module as md

In [46]:
from Module import greeting

In [48]:
greeting('Ahmed')

'Hello Ahmed'

In [34]:
from Shapes import rectange,circle

In [36]:
c1 = circle(5)

In [38]:
print(dir(c1))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'color', 'get_area', 'r']


In [40]:
c1.color

'Red'

In [42]:
c1.get_area()

78.5

In [58]:
# install numpy lib --> windows
!pip install numpy

In [60]:
pip --version

pip 24.0 from C:\Users\LENOVO\anaconda3\Lib\site-packages\pip (python 3.12)

Note: you may need to restart the kernel to use updated packages.


In [ ]:
# linux
!sudo apt-get install python

In [ ]:
#macos
pip3 install numpy

In [62]:
import numpy as np

In [64]:
np.__version__

'1.26.4'

In [66]:
#create numpy array --> 1D array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [72]:
#create numpy array --> 2D array
arr2 = np.array([(1,2,3),(4,5,6),(1,2,3)])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [78]:
#create numpy array --> 3D array
arr3 = np.array([[[1,2,3],[4,5,6],[1,2,3]],[[7,8,9],[10,11,12],[1,2,3]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 1,  2,  3]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 1,  2,  3]]])

In [86]:
a = np.zeros(4,dtype = int)
a

array([0, 0, 0, 0])

In [80]:
a = np.zeros((3,4),dtype = int) #3 rows, 4 columns
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [88]:
a = np.zeros((3,4,7),dtype = int) #3 rows, 4 columns, 7 depth
a

array([[[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]])

In [90]:
np.ones(6,dtype = int)

array([1, 1, 1, 1, 1, 1])

In [104]:
np.arange(10,26,5) #start,end,step

array([10, 15, 20, 25])

In [102]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [108]:
np.full(5,2) #dimension , number to fill the array

array([2, 2, 2, 2, 2])

In [112]:
np.full((4,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [114]:
np.full((4,3,4),7)

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [116]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [118]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [136]:
# random numbers from 0 to 1
np.random.random((2,2))

array([[0.99382305, 0.49239789],
       [0.85630368, 0.12809996]])

In [138]:
np.random.random((7,9))

array([[0.28088903, 0.85244049, 0.22460065, 0.46099328, 0.82635827,
        0.90424294, 0.61277941, 0.6147655 , 0.55758245],
       [0.15476997, 0.20273198, 0.86512204, 0.90603322, 0.30153572,
        0.38676184, 0.93709109, 0.66364576, 0.99906125],
       [0.03843466, 0.73255   , 0.72537003, 0.36176217, 0.21132396,
        0.70380556, 0.78603373, 0.79605126, 0.02139136],
       [0.45258087, 0.92312026, 0.16476496, 0.80887347, 0.23753258,
        0.01390084, 0.69359825, 0.05419606, 0.42366603],
       [0.07462588, 0.41317419, 0.36739145, 0.42901349, 0.82167366,
        0.22919827, 0.33237399, 0.77518339, 0.8735112 ],
       [0.43333451, 0.55231283, 0.90041939, 0.65359117, 0.87246321,
        0.16200981, 0.33363745, 0.17899177, 0.37574   ],
       [0.15534025, 0.764001  , 0.58071161, 0.6786033 , 0.50548638,
        0.62806879, 0.49902342, 0.09972141, 0.50870972]])

In [148]:
np.random.rand(3,2)

array([[0.63495308, 0.10569549],
       [0.84744394, 0.31000164],
       [0.30082463, 0.97948872]])

In [164]:
np.random.randn(5,4)

array([[ 1.31828251, -2.59314745,  0.7515951 ,  1.53702501],
       [-0.28276077,  0.80681779,  0.67378058, -0.45600291],
       [ 0.62591695, -0.41340675, -1.72143505, -0.74807825],
       [ 1.54074742,  0.86681383, -2.11737117,  0.47538812],
       [ 1.01777511,  0.0951918 , -0.13023252,  2.19125406]])

In [176]:
np.random.randint(low = 5,high=50,size=(5,4))

array([[36, 43, 43, 41],
       [16, 17, 38, 38],
       [34, 21, 41, 10],
       [14, 22, 34, 26],
       [16, 20, 32,  7]])

In [179]:
a = np.array([])
a

array([], dtype=float64)

In [185]:
a = np.empty((2,9))
a

array([[9.70530304e-312, 5.53353523e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 1.15998412e-028,
        4.31603868e-080, 1.94919985e-153, 3.98450763e+252],
       [2.25566551e+137, 5.87769019e+135, 1.15874961e-028,
        5.74397461e+107, 2.18229153e-094, 1.43267083e+161,
        2.20832505e-094, 9.80058441e+252, 1.23971686e+224]])

In [193]:
arr = np.full((3,5),8)
arr

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [195]:
arr.shape

(3, 5)

In [199]:
len(arr) # number of rows

3

In [201]:
arr.ndim

2

In [203]:
arr.size #number of elements in array

15

In [209]:
arr.dtype

dtype('int32')

In [211]:
arr.dtype.name

'int32'

In [213]:
a = np.array([1,2,3,4.0])
a

array([1., 2., 3., 4.])

In [215]:
a.dtype

dtype('float64')

In [217]:
a = a.astype(int)
a

array([1, 2, 3, 4])

In [221]:
a = np.array([1,3.4,'a',1])
a

array(['1', '3.4', 'a', '1'], dtype='<U32')

In [223]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [225]:
np.info(np.ndarray.size)

Number of elements in the array.

Equal to ``np.prod(a.shape)``, i.e., the product of the array's
dimensions.

Notes
-----
`a.size` returns a standard arbitrary precision Python integer. This
may not be the case with other methods of obtaining the same value
(like the suggested ``np.prod(a.shape)``, which returns an instance
of ``np.int_``), and may be relevant if the value is used further in
calculations that may overflow a fixed size integer type.

Examples
--------
>>> x = np.zeros((3, 5, 2), dtype=np.complex128)
>>> x.size
30
>>> np.prod(x.shape)
30


In [227]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [229]:
print(a+b)

[ 6  8 10 12]


In [231]:
np.add(a,b)

array([ 6,  8, 10, 12])

In [233]:
print(a-b)

[-4 -4 -4 -4]


In [235]:
np.subtract(a,b)

array([-4, -4, -4, -4])

In [237]:
np.multiply(b,a)

array([ 5, 12, 21, 32])

In [241]:
np.divide(b,a)

array([5.        , 3.        , 2.33333333, 2.        ])

In [243]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [245]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [249]:
np.cos(b)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

In [251]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [253]:
np.exp(b)

array([ 148.4131591 ,  403.42879349, 1096.63315843, 2980.95798704])

In [255]:
a

array([1, 2, 3, 4])

In [257]:
b

array([5, 6, 7, 8])

In [259]:
np.dot(a,b) #5+12+21+32

70

In [261]:
a == b

array([False, False, False, False])

In [263]:
a < 4

array([ True,  True,  True, False])

In [265]:
a.sum()

10

In [267]:
a.min()

1

In [269]:
a.max()

4

In [271]:
a = np.array([[11,10,3,4],[9,6,7,8]])

In [273]:
a

array([[11, 10,  3,  4],
       [ 9,  6,  7,  8]])

In [275]:
a.ndim

2

In [277]:
a.max()

11

In [279]:
a.max(axis =1) #axis =1 --> rows , max number in each row

array([11,  9])

In [281]:
a.max(axis =0) #axis =0 --> column , max number in each column

array([11, 10,  7,  8])

In [283]:
arr = np.array([1,7,9,4,10,20])
arr

array([ 1,  7,  9,  4, 10, 20])

In [285]:
arr.cumsum() # cumlative sum

array([ 1,  8, 17, 21, 31, 51])

In [287]:
arr.mean()

8.5

In [301]:
np.median(arr)

8.0

In [289]:
np.std(arr)

5.9651767227244274

In [291]:
arr_copy = np.copy(arr)

In [293]:
arr_copy

array([ 1,  7,  9,  4, 10, 20])

In [295]:
arr_view = arr.view()
arr_view

array([ 1,  7,  9,  4, 10, 20])

In [297]:
arr.sort()

In [299]:
arr

array([ 1,  4,  7,  9, 10, 20])

In [303]:
arr[0]

1

In [307]:
arr[1:4:2]

array([4, 9])

In [315]:
arr[::-1]

array([20, 10,  9,  7,  4,  1])

In [317]:
arr[arr<5]

array([1, 4])

In [321]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [323]:
arr_t = np.transpose(arr)

In [325]:
arr_t

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [327]:
arr_t2 = arr.T
arr_t2

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [329]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [333]:
arr_1d = np.ravel(arr)
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [335]:
arr_1d.shape

(8,)

In [341]:
new_arr = arr_1d.reshape(2,4)
new_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [343]:
new_arr = arr_1d.reshape(4,2)
new_arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [345]:
new_arr = arr_1d.reshape(5,3)
new_arr

ValueError: cannot reshape array of size 8 into shape (5,3)

In [347]:
a = np.array([[9,1],[2,3]])
a

array([[9, 1],
       [2, 3]])

In [349]:
np.resize(a,(3,3))

array([[9, 1, 2],
       [3, 9, 1],
       [2, 3, 9]])

In [351]:
a = np.array([1,2,3,4,5])
a = np.append(a,(1))
a

array([1, 2, 3, 4, 5, 1])

In [353]:
a = np.append(a,(7,8,9))
a

array([1, 2, 3, 4, 5, 1, 7, 8, 9])

In [355]:
a = np.insert(a,1,30)
a

array([ 1, 30,  2,  3,  4,  5,  1,  7,  8,  9])

In [359]:
a[0] = 40
a

array([40, 30,  2,  3,  4,  5,  1,  7,  8,  9])

In [367]:
a= np.append(a,(1))

In [369]:
a

array([40, 30,  2,  3,  4,  5,  1,  7,  8,  9,  1])

In [371]:
a = np.delete(a,[1])
a

array([40,  2,  3,  4,  5,  1,  7,  8,  9,  1])

In [373]:
a = np.delete(a,[0,1])
a

array([3, 4, 5, 1, 7, 8, 9, 1])